[theme]
primaryColor="#698dea"
backgroundColor="#000000"
secondaryBackgroundColor="#000000"
textColor="#ffffff"

[server]
headless = true
runOnSave = true


[ui]
layout="wide"  # Activa el modo Wide siempre
